import assert from "node:assert/strict";
import fs from "node:fs/promises";

const runnerPath = "maxrun/run_bjt2_ppa_sweep.mjs";
const source = await fs.readFile(runnerPath, "utf8");
const autotopoRunnerPath = "maxrun/run_bjt2_autotopo_ppa_sweep.mjs";
const autotopoSource = await fs.readFile(autotopoRunnerPath, "utf8");

assert.match(source, /DEFAULT_PARALLEL\s*=\s*4/, "bjt2 runner should default to four ngspice jobs");
assert.match(source, /--parallel/, "bjt2 runner should accept a --parallel override");
assert.match(source, /function\s+runPool/, "bjt2 runner should run ngspice jobs through a bounded pool");
assert.match(source, /function\s+stem/, "bjt2 runner should centralize bjt2 stem naming");
assert.match(source, /function\s+isPlotWritePermissionError/, "bjt2 runner should identify plot write permission failures");
assert.match(source, /async\s+function\s+writePlotsBestEffort/, "bjt2 runner should make final plot writes best-effort after numeric deliverables");
assert.match(source, /async\s+function\s+selectWritableArtifactDir/, "bjt2 runner should select a writable artifact directory before invoking ngspice");
assert.match(source, /csv_tmp/, "bjt2 runner should have a writable CSV fallback for locked result directories");
assert.match(source, /raw_tmp/, "bjt2 runner should have a writable raw fallback for locked result directories");
assert.match(source, /plots_tmp/, "bjt2 runner should have a writable plot fallback for locked result directories");
assert.match(source, /selectWritableArtifactDir\(canonicalPlotDir,[\s\S]*"plot"\)/, "bjt2 runner should report when plots use a fallback directory");
assert.match(source, /permission denied/i, "bjt2 runner log scan should catch ngspice file permission failures");
assert.match(source, /ROPAMP/, "bjt2 runner should model the OPAMP follower with a finite-bandwidth pole");
assert.match(source, /COPAMP=\{1\/\(2\*pi\*ROPAMP\*OPAMP_FT\)\}/, "bjt2 runner should derive the OPAMP pole capacitor from OPAMP_FT");
assert.doesNotMatch(source, /EBUF vbuf 0 vout_drv 0 1/, "bjt2 runner should not use an unlimited-bandwidth output follower");
assert.match(source, /row\.high_slope_100k_1meg <= -80/, "bjt2 acceptance gate should enforce the stated -80 dB/dec far-rolloff target");
assert.match(source, /bjt2_sweep_ppa_/, "bjt2 runner should generate bjt2 sweep artifacts");
assert.doesNotMatch(source, /bjt3_sweep_.*_\$\{kind\}\.spice/, "bjt2 runner must not emit bjt3 netlists");
assert.match(source, /bjt2_vs_bjt3_comparison\.csv/, "bjt2 runner should write the final comparison table");

assert.match(autotopoSource, /DEFAULT_PARALLEL\s*=\s*4/, "autotopo runner should default to four ngspice jobs");
assert.match(autotopoSource, /bjt2_autotopo_/, "autotopo runner should generate unique bjt2_autotopo artifact stems");
assert.match(autotopoSource, /run_009/, "autotopo runner should advance to the next run id");
assert.match(autotopoSource, /low_frequency_rolloff_pressure/, "autotopo runner should document the LF-pressure candidate family");
assert.match(autotopoSource, /cinValues = \[33e-9, 47e-9, 56e-9, 68e-9\]/, "autotopo runner should push input coupling capacitance lower to pressure LF slope");
assert.match(autotopoSource, /c12Values = \[33e-9, 47e-9, 56e-9, 68e-9\]/, "autotopo runner should push interstage coupling capacitance lower to pressure LF slope");
assert.match(autotopoSource, /coutValues = \[4\.7e-9, 6\.8e-9, 10e-9\]/, "autotopo runner should sweep output coupling capacitance for another LF pole");
assert.match(autotopoSource, /chValues = \[27e-12, 28e-12\]/, "autotopo runner should keep a narrow run-8 collector capacitor retune grid");
assert.match(autotopoSource, /rbufValues = \[11e3\]/, "autotopo runner should keep the run-8 post-buffer resistor fixed");
assert.match(autotopoSource, /rc: "125k"/, "autotopo runner should preserve the run-8 collector load");
assert.match(autotopoSource, /re: "4\.05k"/, "autotopo runner should preserve the run-8 emitter degeneration");
assert.match(autotopoSource, /cbuf: "180p"/, "autotopo runner should preserve the run-8 post-buffer capacitor");
assert.match(autotopoSource, /opampFt: "175k"/, "autotopo runner should preserve the run-8 OPAMP_FT power point");
assert.match(autotopoSource, /\.param CINVAL=\$\{candidate\.cin\}/, "autotopo runner should parameterize input coupling separately");
assert.match(autotopoSource, /\.param C12VAL=\$\{candidate\.c12\}/, "autotopo runner should parameterize interstage coupling separately");
assert.match(autotopoSource, /rbTop: "4\.7Meg"/, "autotopo runner should preserve the accepted bias divider top leg");
assert.match(autotopoSource, /rbBot: "1Meg"/, "autotopo runner should preserve the accepted bias divider bottom leg");
assert.match(autotopoSource, /LF_SLOPE_PRESSURE_TARGET\s*=\s*60/, "autotopo score should apply a progressive LF slope pressure target");
assert.match(autotopoSource, /lf_rolloff_pressure_penalty/, "autotopo score should include an explicit LF rolloff pressure penalty");
assert.match(autotopoSource, /candidate\.suffix !== "lfrp_rc125k_re4p05k_rb4p7m_cin68n_c12_68n_cout10n_ch27p_r11k_c180p_ft175k"/, "autotopo runner should exclude the exact prior run-8 best from the LF pressure grid");
assert.match(autotopoSource, /capArea\(candidate\.cinNumeric, 1\) \+ capArea\(candidate\.c12Numeric, 1\)/, "autotopo runner should account for separate input and interstage capacitor areas");
assert.doesNotMatch(autotopoSource, /RE2_TOP b2_emitter b2_emit_shaped/, "autotopo runner should restore the unsplit accepted emitter degeneration path");
assert.doesNotMatch(autotopoSource, /CEBYP2 b2_emit_shaped 0/, "autotopo runner should not keep the run-4 emitter bypass capacitor");
assert.match(autotopoSource, /COUT b2_collector vout_drv/, "autotopo runner should restore the accepted single output coupling capacitor");
assert.match(autotopoSource, /bjt2_autotopo_ppa_sweep_summary\.csv/, "autotopo runner should write the required sweep summary");
assert.match(autotopoSource, /bjt2_autotopo_vs_baselines\.csv/, "autotopo runner should write the required baseline comparison");
assert.match(autotopoSource, /bjt2_autotopo_run_index\.csv/, "autotopo runner should append the required run index");
assert.match(autotopoSource, /gain_at_10hz_relative_to_midband_db/, "autotopo summary should include 10 Hz relative gain");
assert.match(autotopoSource, /low_slope_1hz_10hz_db_dec/, "autotopo summary should include low-frequency slope");
assert.match(autotopoSource, /complexity_penalty/, "autotopo score should include a complexity penalty");
assert.match(autotopoSource, /area_ratio_vs_current/, "autotopo score should include area ratio versus the accepted 2BJT");
assert.match(autotopoSource, /power_ratio_vs_current/, "autotopo score should include power ratio versus the accepted 2BJT");
assert.doesNotMatch(autotopoSource, /bjt3_sweep_.*_\$\{kind\}\.spice/, "autotopo runner must not emit bjt3 netlists");

console.log("bjt2 runner structure checks passed");
